---
name: CI

# Controls when the workflow will run
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  staticcheck:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.x"
          check-latest: true
          cache: true

      - run: "go test ./..."
      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2023.1.7"
          install-go: false

  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
        go:
          - 22
    name: "tests on ${{ matrix.platform }} | 1.${{ matrix.go }}.x"
    runs-on: "${{ matrix.platform }}-latest"
    steps:
      # Get the repositery's code
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.${{ matrix.go }}.x"
          cache: true

      - name: Run tests
        run: go clean -testcache && go test -race -cover -covermode=atomic ./...
